### ISSUE TITLE
File Setup

### ISSUE THREAD

**Issue by ledugani** [nss-evening-cohort-7/chatty-pogonophobia#8]
# Story
As a developer, we need files to be created and organized.

# Acceptance Criteria
**When** we pull the repo
**Then** the following files are available in the root:

# Tech Notes
Install Grunt/Setup Browserify
Directories need to be made:
 - index.html
 - javascripts
   - main.js
   - data.js
   - dataGatekeeper.js
   - events.js
   - dom.js
   - messages.js
   - keyPressEvent.js
   - darkThemeEvent.js
   - largeTextTheme.js
   - deleteButtonEvent.js
   - messageClearEvent.js
 - styles
   - main.css
 - db
   - messages.json
 - lib
   - .eslintrc.json
   - Gruntfile.js
 - .gitignore

**Comment by briankw23** [comment]
Task Runner Info

1. cd lib

2 .npm init   (press enter until everything is done)

3. npm install grunt matchdep grunt-contrib-watch grunt-browserify gruntify-eslint --save-dev

4. grunt
